fabrikaR/fabrikar/fabrikar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from questionary.views import *


from rest_framework import routers
from questionary import views

router = routers.DefaultRouter()
router.register(r'quest', views.QuestionaryViewSet)
router.register(r'questions', views.QuestionViewSet)
router.register(r'questiontype', views.QuestionTypeViewSet)
router.register(r'answers', views.AnswerViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', list_questionary, name='list_quest'),
    path('<int:questionary_id>/', quest, name='quest'),
    path('add_questionary/', add_questionary, name='add_quest'),
    path('add_questions/', add_questions, name='add_questions'),
    path('api/', include(router.urls)),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fabrikaR/fabrikar/questionary/models.py
from django.db import models

from django.contrib.auth.models import User

class Questionary(models.Model):
    title = models.CharField(max_length=250, verbose_name='Название опроса')
    start_at = models.DateField(auto_now_add=True, verbose_name='Дата старта')
    end_date = models.DateField(verbose_name='Дата окончания')
    description = models.TextField(blank=True, verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'
        ordering = ['-start_at']


class Question(models.Model):
    quest_text = models.CharField(max_length=250, verbose_name='Текст вопроса')
    question_type = models.ForeignKey('QuestionType', on_delete=models.PROTECT, null=True, verbose_name='Тип ответов')
    questionary = models.ForeignKey(Questionary, on_delete=models.CASCADE, null=True, verbose_name='Опрос')

    def __str__(self):
        return self.quest_text

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Answer(models.Model):
    answer_text = models.CharField(max_length=250, verbose_name='Текст ответа')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True, verbose_name='Вопрос')

    def __str__(self):
        return self.answer_text

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

class QuestionType(models.Model):
    title = models.CharField(max_length=250, verbose_name='Тип вариантов ответов')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тип ответов'
        verbose_name_plural = 'Типы ответов'

class TestQuest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')
    questionary = models.ForeignKey(Questionary, on_delete=models.CASCADE, null=True, verbose_name='Опрос')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True, verbose_name='Вопрос')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True, verbose_name='Ответ')

    class Meta:
        verbose_name = 'Элемент прохождения опроса'
        verbose_name_plural = 'Элементы прохождения опроса'

fabrikaR/fabrikar/questionary/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Questionary, Question, Answer, TestQuest




#  ModelChoiceField Позволяет выбор единственного объекта модели, имеет смысл при отображении внешнего ключа.
class TestQuestCheckboxForm(forms.ModelForm):
    user = forms.ModelChoiceField(label='user', queryset=User.objects.all(), widget=forms.HiddenInput)
    questionary = forms.ModelChoiceField(label='user', queryset=Questionary.objects.filter(pk=48))
    question = forms.ModelChoiceField(label='user', queryset=Question.objects.filter(pk=22))
    answers_set = forms.ModelMultipleChoiceField(queryset=Answer.objects.all(), widget=forms.CheckboxSelectMultiple())
    # questionary = Questionary.objects.get(pk = )
    # choice_field = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    # choice_field.choices
    class Meta:
        model = TestQuest
        fields = '__all__'
        widgets = {

        }

    def save_checkbox_question(self):
        item_form = self.save(commit=False)
        a = self.data.getlist('answers_set')
        for item in a:
            b = Answer.objects.get(pk=item)
            test_quest = TestQuest(answer=b,
                                    questionary=self.cleaned_data['questionary'],
                                    question=self.cleaned_data['question'],
                                    user=self.cleaned_data['user'])
            test_quest.save()


class TestQuestTextForm(forms.ModelForm):
    user = forms.ModelChoiceField(label='user', queryset=User.objects.all())
    questionary = forms.ModelChoiceField(label='user', queryset=Questionary.objects.filter(pk=48))
    question = forms.ModelChoiceField(label='user', queryset=Question.objects.filter(pk=22))
    answer = forms.CharField()
    # questionary = Questionary.objects.get(pk = )
    # choice_field = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    # choice_field.choices
    class Meta:
        model = TestQuest
        fields = '__all__'
        widgets = {

        }
class TestQuestRadioForm(forms.ModelForm):
    user = forms.ModelChoiceField(label='user', queryset=User.objects.all())
    questionary = forms.ModelChoiceField(label='user', queryset=Questionary.objects.filter(pk=48))
    question = forms.ModelChoiceField(label='user', queryset=Question.objects.filter(pk=22))
    answer = forms.ModelChoiceField(queryset=Answer.objects.filter(pk=23), widget=forms.CheckboxSelectMultiple())
    # questionary = Questionary.objects.get(pk = )
    # choice_field = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    # choice_field.choices
    class Meta:
        model = TestQuest
        fields = '__all__'
        widgets = {

        }

class AddQuestionaryForm(forms.ModelForm):
    class Meta:
        model = Questionary
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'style': 'max-width : 300px'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'style': 'max-width : 300px'}),
        }

class AddQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['quest_text', 'question_type']
        widgets = {
            'quest_text': forms.TextInput(attrs={'class':'form-control', 'style': 'max-width : 300px'}),
            'question_type': forms.Select(attrs={'class': 'form-control', 'rows': 5, 'style': 'max-width : 300px'}),
        }

class AddAnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_text']
        widgets = {
            'answer_text': forms.TextInput(attrs={'class':'form-control', 'style': 'max-width : 300px'}),
        }

#  ModelChoiceField Позволяет выбор единственного объекта модели, имеет смысл при отображении внешнего ключа.
# 28.07.2021
# class TestQuestCheckboxForm(forms.ModelForm):
#     user = forms.ModelChoiceField(label='user', queryset=User.objects.all())
#     questionary = forms.ModelChoiceField(label='user', queryset=Questionary.objects.filter(pk=48))
#     question = forms.ModelChoiceField(label='user', queryset=Question.objects.filter(pk=22))
#     answers_set = forms.ModelMultipleChoiceField(queryset=Answer.objects.all(), widget=forms.CheckboxSelectMultiple())
#     # questionary = Questionary.objects.get(pk = )
#     # choice_field = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
#     # choice_field.choices
#     class Meta:
#         model = TestQuest
#         fields = '__all__'
#         widgets = {
#
#         }
#
#     def save_checkbox_question(self):
#         item_form = self.save(commit=False)
#         a = self.data.getlist('answers_set')
#         for item in a:
#             b = Answer.objects.get(pk=item)
#             test_quest = TestQuest(answer=b,
#                                     questionary=self.cleaned_data['questionary'],
#                                     question=self.cleaned_data['question'],
#                                     user=self.cleaned_data['user'])
#             test_quest.save()

fabrikaR/fabrikar/questionary/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from rest_framework import viewsets

from .serializers import *
from django.forms import formset_factory

from django.http import HttpResponseRedirect

from .forms import AddQuestionaryForm, AddQuestionForm, AddAnswerForm, TestQuestCheckboxForm
from .models import Questionary, Question, Answer, TestQuest

class QuestionaryViewSet(viewsets.ModelViewSet):
    queryset = Questionary.objects.all().order_by('start_at')
    serializer_class = QuestionarySerializer

class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all().order_by('id')
    serializer_class = QuestionSerializer

class QuestionTypeViewSet(viewsets.ModelViewSet):
    queryset = QuestionType.objects.all().order_by('id')
    serializer_class = QuestionTypeSerializer

class AnswerViewSet(viewsets.ModelViewSet):
    queryset = Answer.objects.all().order_by('-question')
    serializer_class = AnswerSerializer

def quest(request, questionary_id):
    questionary = Questionary.objects.get(pk=questionary_id)
    questions = Question.objects.filter(questionary=questionary)
    # answers = Answer.objects.filter(question__in=questions)
    answers = Answer.objects.all()
    ArticleFormSet = formset_factory(TestQuestCheckboxForm, extra=2)
    if request.method == 'POST':
        # for item in :
        form = TestQuestCheckboxForm(request.POST)
        # form.questionary = questionary
        a = form.data.getlist('answers_set')
        print(a)
        if form.is_valid():
            form.save_checkbox_question()
    else:
        form = TestQuestCheckboxForm()
    # print(form)
    context = {'questionary': questionary, 'questions': questions, 'answers': answers, 'form': form,
               'ArticleFormSet': ArticleFormSet}
    return render(request, 'questionary/quest.html', context)

# 28/07/2021
# def quest(request, questionary_id):
#     questionary = Questionary.objects.get(pk=questionary_id)
#     questions = Question.objects.filter(questionary=questionary)
#     # answers = Answer.objects.filter(question__in=questions)
#     answers = Answer.objects.all()
#     ArticleFormSet = formset_factory(TestQuestCheckboxForm, extra=2)
#     if request.method == 'POST':
#         # for item in :
#         form = TestQuestCheckboxForm(request.POST)
#         # form.questionary = questionary
#         a = form.data.getlist('answers_set')
#         print(a)
#         if form.is_valid():
#             form.save_checkbox_question()
            # for item in a:
            #     form = TestQuestCheckboxForm(request.POST)
            #     post_form = form.save(commit=False)
            #     post_form2 = form.save(commit=False)
            #     b = Answer.objects.get(pk=item)
            #     print(form.is_bound)
            #     print(item)
            #     print(post_form)
            #     # user = request.user
            #     post_form.answer = b
            #     post_form2.answer = b
            #     post_form.save()
            #     print(TestQuest.answer)
            #     post_form2.save()
            #     print(TestQuest.answer)

    # else:
    #     form = TestQuestCheckboxForm()
    # # print(form)
    # context = {'questionary': questionary, 'questions': questions, 'answers': answers, 'form': form,
    #            'ArticleFormSet': ArticleFormSet}
    # return render(request, 'questionary/quest.html', context)



# def quest(request, questionary_id):
#     questionary = Questionary.objects.get(pk=questionary_id)
#     questions = Question.objects.filter(questionary=questionary)
#     # answers = Answer.objects.filter(question__in=questions)
#     answers = Answer.objects.all()
#     ArticleFormSet = formset_factory(TestQuestCheckboxForm, extra=2)
#     if request.method == 'POST':
#         # for item in :
#         form = TestQuestCheckboxForm(request.POST)
#         # form.questionary = questionary
#         a = form.data.getlist('answers_set')
#         print(a)
#         for item in a:
#             if form.is_valid():
#                 # user = request.user
#                 answer = Answer.objects.get(pk=item)
#                 questionary = form.cleaned_data['questionary']
#                 question = form.cleaned_data['question']
#                 user = form.cleaned_data['user']
#                 TestQuest.objects.create(user=user, questionary=questionary, question=question, answer=answer)
#                     # form.save()
#     else:
#         form = TestQuestCheckboxForm()
#     # print(form)
#     context = {'questionary': questionary, 'questions': questions, 'answers': answers, 'form': form, 'ArticleFormSet': ArticleFormSet}
#     return render(request, 'questionary/quest.html', context)

# def test_questionary(request, questionary_id):
#     if request.method == 'POST':
#         test_quest_form = TestQuestForm(request.POST)
#         questionary = Questionary.objects.get(pk=questionary_id)
#         questions = Question.objects.filter(questionary=questionary)
#         answers = Answer.objects.filter(question__in=questions)
#             if test_quest_form.is_valid():
#                 post_quest = test_quest_form.save(commit=False)
#                 post_quest.user = request.user
#                 post_quest.questionary = questionary.pk
#                 post_quest.question = questions.pk
#                 post_quest.save()
#     else:
#         test_quest_form = TestQuestForm()
#     context = {'quest_form': test_quest_form}
#     return render(request, 'questionary/quest.html', context)

def add_quest(request):
    if request.method == 'POST':
        questionary_form = AddQuestionaryForm(request.POST)
        question_form = AddQuestionForm(request.POST)
        answer_form = AddAnswerForm(request.POST)
        if questionary_form.is_valid():
            post_questionary = questionary_form.save(commit=False)
            post_questionary.save()
            if question_form.is_valid():
                    post_question = question_form.save(commit=False)
                    post_question.questionary = post_questionary
                    post_question.save()
                    if answer_form.is_valid():
                        post_answer = answer_form.save(commit=False)
                        post_answer.question = post_question
                        post_answer.save()
            questionary_form = AddQuestionaryForm()
            question_form = AddQuestionForm()
            answer_form = AddAnswerForm()
            return HttpResponseRedirect('/add_questionary')
    else:
        questionary_form = AddQuestionaryForm()
        question_form = AddQuestionForm()
        answer_form = AddAnswerForm()
    context = {'questionary_form': questionary_form, 'question_form': question_form, 'answer_form': answer_form}
    return render(request, 'questionary/add_questionary.html', context)


def add_questionary(request):
    if request.method == 'POST':
        questionary_form = AddQuestionaryForm(request.POST)
        if questionary_form.is_valid():
            post_questionary = questionary_form.save(commit=False)
            post_questionary.save()
            questionary = post_questionary
            return HttpResponseRedirect('/add_questions')
    else:
        questionary_form = AddQuestionaryForm()
    context = {'questionary_form': questionary_form}
    return render(request, 'questionary/add_questionary.html', context)


def add_questions(request):
    if request.method == 'POST':
        question_form = AddQuestionForm(request.POST)
        answer_form = AddAnswerForm(request.POST)
        if question_form.is_valid():
            post_question = question_form.save(commit=False)
            # post_question.questionary = questionary
            post_question.save()
            if answer_form.is_valid():
                post_answer = answer_form.save(commit=False)
                post_answer.question = post_question
                post_answer.save()

        question_form = AddQuestionForm()
        answer_form = AddAnswerForm()
        return HttpResponseRedirect('/add_questions')
    else:

        question_form = AddQuestionForm()
        answer_form = AddAnswerForm()
    context = {'question_form': question_form, 'answer_form': answer_form}
    return render(request, 'questionary/add_questions.html', context)

def list_questionary(request):
    questionary = Questionary.objects.order_by('-start_at')
    context = {'questionary': questionary, 'title': 'Опросы'}
    return render(request, 'questionary/list_questionary.html', context)

fabrikaR/fabrikar/questionary/templates/questionary/add_questionary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Новый опрос</title>
</head>
<body>

<div class="container" style="margin-top: 5em">
    <h1>Создание опроса</h1>
    <form action="{% url 'add_quest' %}" method="post">
        <div class="row">
            <div class="col-sm-5">

                {% csrf_token %}
                {{ questionary_form.as_p }}
                <button type="submit" class="btn-primary btn-block">Сохранить опрос</button>

            </div>
            <div class="col-sm-7">
                <button id="add_question" class="btn-primary btn-block">Добавить вопрос</button>
                <form action="{% url 'add_quest' %}" method="post">
                    {% csrf_token %}
                    {{ question_form.as_p }}
                    <button id="add_answer" class="btn-primary btn-block">Добавить ответ</button>

                        <form action="{% url 'add_quest' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>
                        <form action="{% url 'add_quest' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>
                        <form action="{% url 'add_quest' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>
                        <form action="{% url 'add_quest' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>

                </form>

            </div>
        </div>
    </form>
</div>
</body>
</html>

fabrikaR/fabrikar/questionary/templates/questionary/add_questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Добавить вопросы</title>


        <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>


<div class="container" style="margin-top: 5em">
    <h1>Добавить вопросы</h1>
    <form action="{% url 'add_questions' %}" method="post">
        <div class="row">
            <div class="col-sm-5">
                <button type="submit" class="btn-primary btn-block">Сохранить опрос</button>

            </div>
            <div class="col-sm-7">
                <button id="add_question" class="btn-primary btn-block">Добавить вопрос</button>
                <form action="{% url 'add_quest' %}" method="post">
                    {% csrf_token %}
                    {{ question_form.as_p }}
                    <button id="add_answer" class="btn-primary btn-block">Добавить ответ</button>

                        <form action="{% url 'add_questions' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>
                        <form action="{% url 'add_questions' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>
                        <form action="{% url 'add_questions' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>
                        <form action="{% url 'add_questions' %}" method="post">
                            {% csrf_token %}
                            {{ answer_form.as_p }}
                        </form>

                </form>

            </div>
        </div>
    </form>
</div>






</body>
</html>

fabrikaR/fabrikar/questionary/templates/questionary/list_questionary.html
{% extends 'base.html' %}

{% block title %}Список опросов{% endblock %}

{% block nav %}{{ block.super }}{% endblock %}

{% block content %}
<h1 style="padding: 20px">Активные опросы</h1>
<div style="max-width: 100%;">
    {% for item in questionary %}
    <div class="card" style="display: grid;  justify-items: center;">
        <div><img src="https://picsum.photos/2000/300" class="img-fluid rounded-start"></div>
        <div class="card-body" style="display: grid;  justify-items: center;">
            <h1 class="card-title">{{ item.title }}</h1>
            <p class="card-text">{{ item.description }}</p>
            <p class="card-text"><small class="text-muted">Создан: {{ item.start_at }} </small></p>
            <p class="card-text"><small class="text-muted">Закончится: {{ item.end_date }}</small></p>
            <a href="/{{ item.pk }}" class="btn btn-warning">Пройти опрос</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

fabrikaR/fabrikar/questionary/templates/questionary/quest.html
{% extends 'base.html' %}

{% block title %}{{ questionary.title }}{% endblock %}

{% block nav %}{{ block.super }}{% endblock %}

{% block content %}


<h1 style="padding-left: 50px; padding-top: 50px">{{ questionary.title }} </h1>

<form method="post">

    {% csrf_token %}
<!--    {% for form_item in ArticleFormSet %}-->
<!--        {{ ArticleFormSet}}-->
<!--    {% endfor %}-->

    {{ form.as_p }}
    <button type="submit" class="btn btn-warning">Пройти опрос</button>

</form>


{% endblock %}

<!--    <tr><th><label for="id_user">Gjkm</label></th><td>-->
<!--        <input class="form-check-input" type="hidden" name="user" required id="id_user" value="1">-->

<!--<tr><th><label for="id_questionary">{{ questionary.title}}</label></th><td>-->
<!--    <input class="form-check-input" type="hidden" name="questionary" required id="id_questionary" value="{{ questionary.pk }}">-->

<!--    <div style="display: grid; justify-items: center;">-->
<!--        {% for item in questions %}-->
<!--            <div style="display: grid; justify-items: center;">-->
<!--                <h1 class="card-title">{{ item.quest_text }}</h1>-->
<!--                <input class="form-check-input" type="hidden" name="question" required id="id_question" value="{{ item.pk }}">-->
<!--                {% for a_item in answers %}-->
<!--                    {% if a_item.question == item %}-->
<!--                        {% if item.question_type.title == 'Ответ с одним вариантом' %}-->
<!--                            {{ form.as_p }}-->
<!--                            <div class="form-check">-->
<!--&lt;!&ndash;                                <input class="form-check-input" type="radio" name="gridRadios" id="{{ a_item.id }}" value="{{ a_item.pk }}">&ndash;&gt;-->
<!--                                <input class="form-check-input" type="radio" name="gridRadios" id="{{ a_item.pk }}" value="{{ a_item.pk }}" required>-->
<!--                                <label class="form-check-label" for="gridRadios2">-->
<!--                                    {{ a_item.answer_text }}-->
<!--                                </label>-->
<!--                            </div>-->
<!--                        {% endif %}-->

<!--                        {% if item.question_type.title == 'Ответ текстом' %}-->
<!--                            {{ form.as_p }}-->
<!--                            <div class="form-floating" style="max-width: 700px">-->
<!--                                <textarea class="form-control" placeholder="Ваш ответ:" id="floatingTextarea"></textarea>-->
<!--                                <label for="floatingTextarea">Ваш ответ:</label>-->
<!--                            </div>-->
<!--                        {% endif %}-->

<!--                        {% if item.question_type.title == 'Чек-бокс' %}-->

<!--                            {{ form.as_p }}-->

<!--                            <div class="input-group" style=" display: grid; justify-items: center; max-width: 300px">-->
<!--                                <div style="display: flex; align-items: center;">-->
<!--                                    <div class="form-check">-->
<!--                                        <input class="form-check-input" type="checkbox" id="inlineFormCheck">-->
<!--                                        <label class="form-check-label" for="inlineFormCheck">-->
<!--                                           {{ a_item.answer_text }}-->
<!--                                        </label>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        {% endif %}-->

<!--                    {% endif %}-->
<!--                {% endfor %}-->
<!--            </div>-->
<!--            <hr>-->
<!--        {% endfor %}-->
<!--        <div>-->

<!--        </div>-->
<!--    </div>-->



<!--<tr><th><label for="id_user">user:</label></th><td><select name="user" required id="id_user">-->
<!--  <option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->

<!--  <option value="1" selected>admin</option>-->

<!--</select></td></tr>-->
<!--<tr><th><label for="id_questionary">user:</label></th><td><select name="questionary" required id="id_questionary">-->
<!--  <option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->

<!--  <option value="48" selected>Киноопрос</option>-->

<!--</select></td></tr>-->
<!--<tr><th><label for="id_question">user:</label></th><td><select name="question" required id="id_question">-->
<!--  <option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->

<!--  <option value="22" selected>Поговорим о том, о сём?</option>-->

<!--</select></td></tr>-->
<!--<tr><th><label>Answer:</label></th><td><ul class="errorlist"><li>Выберите корректный вариант. Вашего варианта нет среди допустимых значений.</li></ul><ul id-->
<!--="id_answer">-->
<!--    <li><label for="id_answer_0"><input type="checkbox" name="answer" value="" id="id_answer_0">-->
<!-- -&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</label>-->

<!--</li>-->
<!--    <li><label for="id_answer_1"><input type="checkbox" name="answer" value="22" id="id_answer_1">-->
<!-- 1</label>-->

<!--</li>-->
<!--    <li><label for="id_answer_2"><input type="checkbox" name="answer" value="23" id="id_answer_2">-->
<!-- 123</label>-->

<!--</li>-->
<!--    <li><label for="id_answer_3"><input type="checkbox" name="answer" value="24" id="id_answer_3">-->
<!-- Дадада</label>-->

<!--</li>-->
<!--    <li><label for="id_answer_4"><input type="checkbox" name="answer" value="25" id="id_answer_4" checked>-->
<!-- Криминальное чтиво</label>-->

<!--</li>-->
<!--    <li><label for="id_answer_5"><input type="checkbox" name="answer" value="26" id="id_answer_5">-->
<!-- Пиратские фильмы</label>-->

<!--</li>-->
<!--    <li><label for="id_answer_6"><input type="checkbox" name="answer" value="27" id="id_answer_6">-->
<!-- Гарри Поттер</label>-->

<!--</li>-->
<!--    <li><label for="id_answer_7"><input type="checkbox" name="answer" value="28" id="id_answer_7">-->
<!-- Всегда говори &quot;Да&quot;</label>-->

<!--</li>-->
<!--</ul></td></tr>-->